### Site info:
title: Luffy--Tec. Blog
tagline: Fresh Data Nerd, Life Adventurist
author: learned from Lijia Yu
email: ludafei@dratio.com
description: "This is a personal blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Luffy, Data"
baseurl: "/luffy" # the subpath of your site, e.g. /blog
url: "http://ludafei.com/luffy" # the base hostname & protocol for your site
locale: Chaoyang Beijing, China

### Personal info and site tools info:
twitter_username: da_luffy
github_username:  luffy1121
disqus_shortname: LuFFy
favicon:     "/images/luffy.jpeg"
aboutme: Hi, this is Luffy, a fresh Data Nerd. Please enjoy my personal blog. # these are shown on aboutme-sidebar.
aboutme_photo: http://img4q.duitang.com/uploads/item/201301/06/20130106192159_44Q4X.jpeg


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Rlogger
      href: http://www.r-bloggers.com/
      title: An interesting R user Blog
    - name: Python Information Post
      href: http://python.memect.com/
      title: An interesting Python Blog


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
